---
# Remove EXTERNALLY-MANAGED file if we're on Debian12
# Related issue: https://github.com/geerlingguy/ansible-role-pip/issues/57
- name: Get Python 3.X version
  ansible.builtin.command: python3 --version
  register: pyver
  changed_when: false
  failed_when: pyver.rc != 0

- name: Remove Python 3.X EXTERNALLY-MANAGED file
  ansible.builtin.file:
    state: absent
    path: "/usr/lib/python{{ pyver.stdout.split()[1] | regex_search('([0-9]+\\.[0-9]+)') }}/EXTERNALLY-MANAGED"
  when: pyver.stdout | regex_search('3\.[0-9]+')
