---
- name: Prepare
  hosts: all
  become: true
  # become_method: su
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - role: buluma.bootstrap
    - role: buluma.setuptools
    - role: buluma.openssl
    - role: buluma.ca_certificates
